#!/usr/bin/env node
'use strict';

/**
 * @file scaffold.js
 * @description Creates a new nilix custom project skeleton.
 *
 * Usage (after sourcing vars):
 *   scaffold <project-name> [options]
 *
 * Or directly:
 *   node utils/scaffold.js <project-name> [options]
 *
 * Options:
 *   --dest=DIR        Parent directory for the project container
 *                     (default: current directory)
 *   --port=NUM        Server port  (default: 3001)
 *   --version=STR     Version tag appended to container dir  (default: v000)
 *   --help, -h        Show this help message
 *
 * Creates:
 *   <dest>/<name>_<version>/
 *     <name>/         ← app directory
 *       .env
 *       menu.xml
 *       form/
 *       apps/
 *       reports/
 *       dbase/
 *       data/
 *       logs/
 *       init-app.js
 *       setup.js
 *       start.js
 *     nilix            ← symlink to NILSRC (or resolved engine path)
 *
 * Requirements:
 *   - NILSRC env var must be set (source vars from the nilix root)
 *   - Or run from inside the nilix directory
 */

const path   = require('path');
const fs     = require('fs');
const crypto = require('crypto');

// ── Help ──────────────────────────────────────────────────────────────────────

const HELP = `
scaffold — create a new nilix custom project

Usage:
  scaffold <project-name> [options]

Options:
  --dest=DIR      Parent directory for the project container
                  (default: current directory)
  --port=NUM      Server port (default: 3001)
  --version=STR   Version tag appended to the container folder (default: v000)
  --help, -h      Show this message

Creates:
  <dest>/<project-name>_<version>/
    <project-name>/     ← app directory
      .env              ← config with generated JWT secret
      menu.xml          ← minimal menu template
      form/             ← XML form definitions
      apps/             ← JS handlers
      reports/          ← YAML report definitions
      dbase/            ← app SQLite database (created by init-app.js)
      data/             ← auth.db (managed by engine)
      logs/             ← log files (auto-rotated, 30 days)
      init-app.js       ← app DB schema (fill in your tables)
      setup.js          ← first-run setup wrapper
      start.js          ← server start wrapper
    nilix               ← symlink to nilix engine (NILSRC)

Workflow after scaffolding:
  cd <dest>/<project-name>_<version>/<project-name>
  node setup.js       # init JWT secret + auth.db + app DB
  node start.js       # start the server
  # Open /nil-setup in browser to create the first empresa + user
`.trim();

// ── Arg parsing ───────────────────────────────────────────────────────────────

function parseArgs(argv) {
    const args   = argv.slice(2);
    const opts   = { dest: null, port: '3001', version: 'v000', name: null };
    const extras = [];

    for (const arg of args) {
        if (arg === '--help' || arg === '-h') { console.log(HELP); process.exit(0); }
        const m = arg.match(/^--(\w+)=(.+)$/);
        if (m) {
            opts[m[1]] = m[2];
        } else if (!arg.startsWith('-')) {
            extras.push(arg);
        } else {
            bail(`Unknown option: ${arg}`);
        }
    }

    opts.name = extras[0] ?? null;
    return opts;
}

function bail(msg) {
    console.error(`❌  ${msg}`);
    console.error('    Run scaffold --help for usage.');
    process.exit(1);
}

// ── Template generators ───────────────────────────────────────────────────────

function makeDotEnv(name, port, secret) {
    return [
        `# ${name} — nilix project config`,
        `# Generated by scaffold on ${new Date().toISOString().split('T')[0]}`,
        '',
        `NIL_ENGINE_PATH=../nilix`,
        `NIL_MENU_FILE=menu.xml`,
        `NIL_DB_FILE=dbase/${name}.db`,
        `NIL_AUTH_DB=data/auth.db`,
        `NIL_JWT_SECRET=${secret}`,
        `NIL_JWT_EXPIRY=8h`,
        `NIL_PORT=${port}`,
    ].join('\n') + '\n';
}

function makeMenuXml(name) {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  ${name} — main menu
  Every entry is a <option> tag — <item> is silently ignored by the parser
  (src/services/menuService.js), the menu would render empty.
  types: form | report | separator | menu (submenu)
  permissions: R=read  A=add  D=delete  U=update
               RADU = full access  |  R = read-only
-->
<menu id="${name}" title="${name.toUpperCase()}">
    <option type="separator" label="${name.toUpperCase()}"/>
    <!--
    <option type="form"   label="Example"      target="form/example.xml"      permissions="RADU"/>
    <option type="report" label="Example Rep"  target="reports/example.yaml"  permissions="R"/>
    -->
</menu>
`;
}

function makeInitApp(name) {
    return `#!/usr/bin/env node
'use strict';

/**
 * @file init-app.js
 * @description Creates the application database for ${name}.
 *
 * Usage:
 *   node init-app.js
 *
 * Run via setup.js — do not run directly unless you want to reset the DB.
 */

const path    = require('path');
const fs      = require('fs');
const readline = require('readline');

// ── Load .env ─────────────────────────────────────────────────────────────────
const ENV_PATH = path.join(__dirname, '.env');
if (fs.existsSync(ENV_PATH)) {
    for (const line of fs.readFileSync(ENV_PATH, 'utf8').split('\\n')) {
        const t = line.trim();
        if (!t || t.startsWith('#')) continue;
        const eq = t.indexOf('=');
        if (eq < 1) continue;
        const k = t.slice(0, eq).trim();
        const v = t.slice(eq + 1).trim();
        if (!(k in process.env)) process.env[k] = v;
    }
}

const ENGINE_PATH = process.env.NIL_ENGINE_PATH
    ? (path.isAbsolute(process.env.NIL_ENGINE_PATH)
        ? process.env.NIL_ENGINE_PATH
        : path.resolve(__dirname, process.env.NIL_ENGINE_PATH))
    : path.resolve(__dirname, '../nilix');

const sql = require(path.join(ENGINE_PATH, 'node_modules', 'sql.js'));

async function init() {
    const dbPath = process.env.NIL_DB_FILE
        ? (path.isAbsolute(process.env.NIL_DB_FILE)
            ? process.env.NIL_DB_FILE
            : path.resolve(__dirname, process.env.NIL_DB_FILE))
        : path.join(__dirname, 'dbase/${name}.db');

    // ── Guard: confirm before overwriting ────────────────────────────────────
    if (fs.existsSync(dbPath)) {
        const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
        await new Promise(resolve => {
            rl.question(\`⚠️  \${dbPath} already exists. Overwrite? (type RESET to confirm): \`, answer => {
                rl.close();
                if (answer.trim() !== 'RESET') {
                    console.log('Cancelled — database unchanged.');
                    process.exit(0);
                }
                resolve();
            });
        });
    }

    const dbDir = path.dirname(dbPath);
    if (!fs.existsSync(dbDir)) fs.mkdirSync(dbDir, { recursive: true });

    const SQL = await sql.default();
    const db  = new SQL.Database();
    db.run('PRAGMA foreign_keys = ON;');

    // ── Define your tables here ───────────────────────────────────────────────
    // All tables that are tenant-scoped must include:
    //   empresa_id INTEGER NOT NULL
    //
    // Example:
    //
    // db.run(\`
    //     CREATE TABLE clientes (
    //         id_cliente      INTEGER PRIMARY KEY AUTOINCREMENT,
    //         empresa_id      INTEGER NOT NULL,
    //         nombre_completo TEXT    NOT NULL,
    //         telefono        TEXT,
    //         email           TEXT
    //     )
    // \`);

    // ── Save ──────────────────────────────────────────────────────────────────
    const data = db.export();
    fs.writeFileSync(dbPath, Buffer.from(data));
    console.log(\`✅  \${dbPath} created.\`);
}

init().catch(err => { console.error(err); process.exit(1); });
`;
}

function makeSetupJs() {
    return `#!/usr/bin/env node
'use strict';

/**
 * @file setup.js
 * @description First-run setup for this nilix project.
 *
 * Steps:
 *   1. Generates NIL_JWT_SECRET in .env if missing
 *   2. Initializes auth.db via the engine
 *   3. Initializes the app database via init-app.js
 *
 * Usage:
 *   node setup.js
 */

process.env.NIL_APP_DIR = __dirname;
require('../nilix/utils/nil-setup.js');

// Step 3 — app-specific DB schema
console.log('🗄️   Initializing app database...');
require('./init-app.js');
`;
}

function makeStartJs() {
    return `#!/usr/bin/env node
'use strict';

/**
 * @file start.js
 * @description Starts the nilix engine with this project's configuration.
 *
 * Usage:
 *   node start.js
 */

process.env.NIL_APP_DIR = __dirname;
require('../nilix/utils/nil-start.js');
`;
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
    const opts = parseArgs(process.argv);

    if (!opts.name) bail('Missing required argument: <project-name>');
    if (!/^[a-zA-Z][a-zA-Z0-9_-]*$/.test(opts.name)) bail('project-name must start with a letter and contain only letters, numbers, _ or -');
    if (!/^\d+$/.test(opts.port))    bail(`--port must be a number (got: ${opts.port})`);
    if (!/^\w+$/.test(opts.version)) bail(`--version must be alphanumeric (got: ${opts.version})`);

    const destBase  = opts.dest ? path.resolve(opts.dest) : process.cwd();
    const container = path.join(destBase, `${opts.name}_${opts.version}`);
    const appDir    = path.join(container, opts.name);

    // Resolve nilix path for symlink
    const nilixSrc = process.env.NILSRC
        ?? (fs.existsSync(path.join(__dirname, '..', 'server.js'))
            ? path.resolve(__dirname, '..')  // running from inside nilix/utils/
            : null);

    if (!nilixSrc) bail('NILSRC is not set. Source the vars file first:\n    . ./vars');

    // ── Create directories ────────────────────────────────────────────────────
    if (fs.existsSync(container)) bail(`Directory already exists: ${container}`);

    for (const dir of [
        appDir,
        path.join(appDir, 'form'),
        path.join(appDir, 'apps'),
        path.join(appDir, 'reports'),
        path.join(appDir, 'dbase'),
        path.join(appDir, 'data'),
        path.join(appDir, 'logs'),
    ]) {
        fs.mkdirSync(dir, { recursive: true });
    }

    // ── Symlink nilix ─────────────────────────────────────────────────────────
    const symlinkPath = path.join(container, 'nilix');
    fs.symlinkSync(nilixSrc, symlinkPath);

    // ── Generate files ────────────────────────────────────────────────────────
    const secret = crypto.randomBytes(32).toString('hex');

    fs.writeFileSync(path.join(appDir, '.env'),        makeDotEnv(opts.name, opts.port, secret));
    fs.writeFileSync(path.join(appDir, 'menu.xml'),    makeMenuXml(opts.name));
    fs.writeFileSync(path.join(appDir, 'init-app.js'), makeInitApp(opts.name));
    fs.writeFileSync(path.join(appDir, 'setup.js'),    makeSetupJs());
    fs.writeFileSync(path.join(appDir, 'start.js'),    makeStartJs());

    // ── Report ────────────────────────────────────────────────────────────────
    console.log(`\n✅  Project created: ${container}\n`);
    console.log(`    ${opts.name}_${opts.version}/`);
    console.log(`      ${opts.name}/`);
    console.log(`        .env          (NIL_PORT=${opts.port}, JWT secret generated)`);
    console.log(`        menu.xml      (minimal template)`);
    console.log(`        init-app.js   (fill in your DB schema)`);
    console.log(`        setup.js`);
    console.log(`        start.js`);
    console.log(`        form/  apps/  reports/  dbase/  data/  logs/`);
    console.log(`      nilix  →  ${nilixSrc}`);
    console.log(`\n  Next steps:`);
    console.log(`    cd ${appDir}`);
    console.log(`    # Edit init-app.js — define your tables`);
    console.log(`    node setup.js       # init JWT + auth.db + app DB`);
    console.log(`    node start.js       # start the server`);
    console.log(`    # Open /nil-setup in browser — create first empresa + user\n`);
}

main();
